### ISSUE TITLE
Create image steganography toolbox

### ISSUE THREAD

**Issue by osteele** [sd17spring/Toolbox-ImageSteganography#1]
I spent some time today writing an image steganography toolbox. Can someone take a look at the writeup I did for it in addition to the starter code?

https://github.com/sd17spring/sd17spring.github.io/blob/steganography_rev/_toolboxes/image-steganography.md

https://github.com/sd17spring/Toolbox-ImageSteganography
 
Solution set is here:

https://github.com/srli/image_steganography

**Comment by srli** [comment]
Code has been reviewed and committed.
